//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDDigital.DiarioAcademia.Dominio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDDigital.DiarioAcademia.Dominio.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum aluno encontrado para a turma de {0}.
        /// </summary>
        public static string EXCEPTION_NENHUM_ALUNO_ENCOTRADO_PARA_TURMA {
            get {
                return ResourceManager.GetString("EXCEPTION_NENHUM_ALUNO_ENCOTRADO_PARA_TURMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma aula encontrada para esta data {0}.
        /// </summary>
        public static string EXCEPTION_NENHUMA_AULA_ENCOTRADA_NESTA_DATA {
            get {
                return ResourceManager.GetString("EXCEPTION_NENHUMA_AULA_ENCOTRADA_NESTA_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Ocorreu um erro, verifique se esta turma tem alunos relacionados&quot;.
        /// </summary>
        public static string EXCEPTION_TURMA_COM_ALUNOS_RELACIONADOS {
            get {
                return ResourceManager.GetString("EXCEPTION_TURMA_COM_ALUNOS_RELACIONADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alunos/Presenças/Faltas:.
        /// </summary>
        public static string RELATORIO_DESCRICAO {
            get {
                return ResourceManager.GetString("RELATORIO_DESCRICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório de presenças - Academia do prgramador.
        /// </summary>
        public static string RELATORIO_TITULO {
            get {
                return ResourceManager.GetString("RELATORIO_TITULO", resourceCulture);
            }
        }
    }
}
